### ISSUE TITLE
Lỗi user/sign_out không ổn định.

### ISSUE THREAD

**Issue by DucVinhDang** [MedianNguyen/die4top-library#26]
Khi đăng nhập một user, user/sign_in hoạt động bình thường (đăng nhập phát ăn luôn), nhưng khi đăng suất, user/sign_out bị báo lỗi không tìm thấy route
### No route matches [DELETE] "/users/sign_out"
Nhưng rõ ràng trong danh sách route vẫn tồn tại path đó.
```
new_user_session_path	GET	/users/sign_in(.:format)	devise/sessions#new
user_session_path	POST	/users/sign_in(.:format)	devise/sessions#create
destroy_user_session_path	GET	/users/sign_out(.:format)	devise/sessions#destroy
user_password_path	POST	/users/password(.:format)	devise/passwords#create
```
Và enter lại đường link http://localhost:3000/users/sign_out ngay sau lúc lỗi thì lại sign out đc.
Em không hiểu lỗi ở chỗ nào ạ?

**Comment by quyetdc** [comment]
Done, pushed code to old state
