### ISSUE TITLE
Tạo trang category

### ISSUE THREAD

**Issue by quyetdc** [MedianNguyen/die4top-library#30]
- Tìm template hiển thị books, ảnh ... để tạo trang category và về sau dùng cho 1 số trang khác :-) có thể dùng lại những gì đang có cũng được
- Hiển thị sách thuộc category đó.
- Đẩy dữ liệu thật vào sidebar mục category
- Đẩy _leftbar layout vào application.html.rb thay vì ở home/index.html.rb như hiện tại

**Comment by MedianNguyen** [comment]
Assign tasks (user stories) ở Trello.
Github để fix bug và merge code thôi:
https://trello.com/b/78DGMrrL/die4top-library
